import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => ios,
      TargetPlatform.windows => windows,
      TargetPlatform.linux => windows,
      _ => android,
    };
  }

  // Replace with values generated by: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'replace-me',
    appId: '1:1234567890:web:replace-me',
    messagingSenderId: '1234567890',
    projectId: 'smartnutri-dev',
    authDomain: 'smartnutri-dev.firebaseapp.com',
    storageBucket: 'smartnutri-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'replace-me',
    appId: '1:1234567890:android:replace-me',
    messagingSenderId: '1234567890',
    projectId: 'smartnutri-dev',
    storageBucket: 'smartnutri-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'replace-me',
    appId: '1:1234567890:ios:replace-me',
    messagingSenderId: '1234567890',
    projectId: 'smartnutri-dev',
    storageBucket: 'smartnutri-dev.appspot.com',
    iosBundleId: 'com.smartnutri.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'replace-me',
    appId: '1:1234567890:web:windows-replace-me',
    messagingSenderId: '1234567890',
    projectId: 'smartnutri-dev',
    authDomain: 'smartnutri-dev.firebaseapp.com',
    storageBucket: 'smartnutri-dev.appspot.com',
  );
}
