// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3imUN5YGKHRKbrr65ibsu2hQ6D3K2ii8',
    appId: '1:317078492765:web:3602b9942f6cb4bc5f9fb4',
    messagingSenderId: '317078492765',
    projectId: 'smartnutri-dev-2e67b',
    authDomain: 'smartnutri-dev-2e67b.firebaseapp.com',
    storageBucket: 'smartnutri-dev-2e67b.firebasestorage.app',
    measurementId: 'G-Y0MVMLWHGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHaF4gipOQZQudctuNwT0rGuY2LwwDS4',
    appId: '1:317078492765:android:5a4147644e4aaf535f9fb4',
    messagingSenderId: '317078492765',
    projectId: 'smartnutri-dev-2e67b',
    storageBucket: 'smartnutri-dev-2e67b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_enhGHBaNb0lzLxU94Ty-Iw4QYEuVYfU',
    appId: '1:317078492765:ios:f3a6082f4ef8d83c5f9fb4',
    messagingSenderId: '317078492765',
    projectId: 'smartnutri-dev-2e67b',
    storageBucket: 'smartnutri-dev-2e67b.firebasestorage.app',
    iosBundleId: 'com.example.smartnutri',
  );
}
